### ISSUE TITLE
Pourquoi dans la section PHP les tutos de grafikart ne sont pas inclus en recommandation 

### ISSUE THREAD

**Issue by Havet57** [learndev-info/awesome-learning-dev-fr#105]
Bonjour, 

alors je lis/pratique actuellement le livre de Pierre Giraud cours complet php mysql, cependant je commence doucement à n'en plus pouvoir. Je me suis donc dis que j'allais suivre un format vidéo sur you tube, et je tombe sur une playlist de plus de 60 vidéos de grafikart sur php. 
Pourquoi ça ne rentre pas dans la liste des ressources en php ? 
Qu'est-ce qui manque ? Qu'est-ce qui ne va pas ? Quelle méthodologie est discutable ? 

Ce sont des questions sincères car ça m'ennuierait beaucoup d'apprendre des choses fausses ou problématiques ! :) 

Merci pour votre travail d'information,

**Comment by rault-a** [comment]
Bonjour,

Il me semble que le cours de grafikart n'est pas toujours complètement à jour, mais reste une bonne référence. Si tu utilises son cours, n'hésite pas à rejoindre son discord pour demander confirmation.
