### ISSUE TITLE
VSCode now available for Linux // VSCode maintenant disponible pour Linux

### ISSUE THREAD

**Issue by Aventure20** [learndev-info/awesome-learning-dev-fr#109]
<h3>English</h3>

VSCode is available for Linux running Debian, Ubuntu, Red Hat, Fedora, SUSE, and other Linux distributions. You can download it from the official website or from the Snap Store. So, please, correct "The IDEs" part.
Have a nice day. Thanks you. Aventure20.
<h3>Français</h3>

VSCode est disponible pour Linux sous Debian, Ubuntu, Red Hat, Fedora, SUSE, et d'autres distributions de Linux. Vous pouvez le télécharger depuis le site officiel ou depuis le Snap Store. Donc, s'il vous plaît, corriger la partie "Les IDEs".
Bonne journée. Merci. Aventure20.
<h3>Sources</h3>

https://code.visualstudio.com/#alt-downloads

**Comment by rault-a** [comment]
Bonjour

Visual Studio et Visual Studio Code sont 2 choses différentes. Visual Studio Code est en effet disponible sur linux, mais pas Visual Studio à ma connaissance.

**Comment by Aventure20** [comment]
Bonjour,
effectivement Visual Studio n'est pas disponible pour Linux. 
Désolé du dérangement. 
Merci. Aventure20.
