### ISSUE TITLE
Add section for frameworks

### ISSUE THREAD

**Issue by IvanDelsinne** [learndev-info/awesome-learning-dev-fr#22]
As an example, there's two big known frameworks: ASP.NET and Java Spring (both for backend web development).

The thing is, those frameworks are awesome to use, complete, but hard to take on, and there's a lot of good, and bad, resources out there.

For Java Spring, I can provide a few resources for learning:

- [Learning Spring boot 2.0](https://www.packtpub.com/application-development/learning-spring-boot-20-second-edition), paid book
- [Baeldung](https://www.baeldung.com/), separated in clear categories, and maintained up to date

**Comment by rault-a** [comment]
Seems a bit out of scope to me
