### ISSUE TITLE
add freecodecamp

### ISSUE THREAD

**Issue by MaxxHim** [learndev-info/awesome-learning-dev-fr#26]
Bonjour, 
Je me permet de proposer un site que j'ai découvert récemment : https://www.freecodecamp.org/
Uniquement en anglais qui propose un grand nombre de tutoriels sous forme d'exercice.

**Comment by exybore** [comment]
Ce site a l'air vraiment pas mal, surtout qu'il met dès le début les apprentis dans des situation de cas pratiques.

**Comment by rault-a** [comment]
Added :)
