### ISSUE TITLE
pourquoi openclassrooms est il à éviter ?

### ISSUE THREAD

**Issue by Zinavolia** [learndev-info/awesome-learning-dev-fr#28]
pourquoi openclassrooms est il à éviter ?

**Comment by exybore** [comment]
@Zinavolia Les tutoriels d'OpenClassrooms sont pour la plupart dépassés. En effet, ils ont été écrits il y a longtemps, et certaines technologies (PHP 5, JQuery...) ne sont plus d'actualité. 
De plus, il y a beaucoup de mauvaises pratiques qui y sont enseignées, comme l'utilisation de la méthode de chiffrement SHA-1.
Il est donc préférable de privilégier l'utilisation de sites de confiance, renseignés sur Awesome Learning Dev.
