### ISSUE TITLE
[Readability] Add websites' names beside links

### ISSUE THREAD

**Issue by Razakhel** [learndev-info/awesome-learning-dev-fr#40]
It would improve readability to know in a glance where the links redirect to.

Some possible examples:

---

[Tutoriel/Cours](https://zestedesavoir.com/tutoriels/755/le-langage-c-1/) (Zeste de Savoir)
[Cours](https://books.goalkicker.com/CBook/) - GoalKicker
[Guide complet](https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps) [Mozilla]

**Comment by rault-a** [comment]
Done
