### ISSUE TITLE
Would you like to list React courses?

### ISSUE THREAD

**Issue by jadjoubran** [learndev-info/awesome-learning-dev-fr#57]
Hey!

I wanted to submit a PR, but would like to get your opinion first.
Last year you've shared my course, [Learn JavaScript](https://learnjavascript.online) to the list. Thank you for that!
If you're interested in adding a **React** section, I can send a PR for a new section called **Frontend libraries/frameworks**
The new course is called [React Tutorial](https://react-tutorial.app)

**Comment by rault-a** [comment]
Hi,
I personnaly think that it would be a bit out of scope and would better fit an awesome list dedicated to javascript (or front end web development), the goal here would be to stick to languages themselves.

**Comment by jadjoubran** [comment]
Makes sense, thanks 👍
